# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b27beb3ac472be9c8a1df688ccf7ee7afd52124e3c43d76c7173b4b2b89324dbc1555ee4f136515f4124c4c63012da1531ecc88c313bce388cb38221e0c67467

test:
  secret_key_base: fc423d79032bbf5d4bc66d634db5da5096a41171c2097edbd87b447d2b5b07d32827b9795055751a77e3d21751cc66028e634cdfae26589fbd43ba640c3fed8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
